### PR TITLE
made a .gitignore and JSON file for dependencies

### PR DESCRIPTION
**Pull request by miriam30**

### CODE REVIEW

**Comment by miriam30** [comment]
first merge

**Comment by Beagbarreto** [comment]
Accept first merge

**Comment by HeberGutierrez** [comment]
I agree the file.

**Review by Edward060290 — APPROVED** [review]

**Review by Beagbarreto — APPROVED** [review]
It's approved

**Review by HeberGutierrez — APPROVED** [review]

**Pull request merged**
